### ISSUE TITLE
No check if existing extensions are installed

### ISSUE THREAD

**Issue by DavidBruchmann** [helhum/ajax_example#15]
The eid-mechanism fails if an extension with some problem(s) is existing in the ext-path even if it's not installed. So a check should be included ...

**Comment by DavidBruchmann** [comment]
As example I've an extension where the labels in BE are written by a hooked function.
The Backtrace is then:
`
TYPO3\\CMS\\Core\\Utility\\GeneralUtility::callUserFunction#80 // 
 call_user_func_array#4315 // 
TYPO3\\CMS\\Backend\\Form\\Element\\InlineElement->processAjaxRequest# // 
call_user_func_array#1073 // 
TYPO3\\CMS\\Backend\\Form\\Element\\InlineElement->createNewRecord# // 
TYPO3\\CMS\\Backend\\Form\\Element\\InlineElement->renderForeignRecord#1269 // 
TYPO3\\CMS\\Backend\\Form\\Element\\InlineElement->renderForeignRecordHeader#472 // 
TYPO3\\CMS\\Core\\Utility\\GeneralUtility::callUserFunction#564 // 
call_user_func_array#4315 // 
Vendor\\MyExtension\\TCA\\TcaLabels->getLabel# // 
TYPO3\\CMS\\Core\\Database\\DatabaseConnection->exec_SELECTgetSingleRow#560 // 
TYPO3\\CMS\\Core\\Database\\DatabaseConnection->exec_SELECTquery#406 // 
TYPO3\\CMS\\Core\\Database\\DatabaseConnection->debug#305
`
As the hook is read from the NOT INSTALLED extension but the table not in TCA this fails, I suppose no matter if there is a fault or not in the extension.

**Comment by DavidBruchmann** [comment]
Still to remark that the Error-Message with backtrace is shown in FE, where the hooked function never should be called at all.

**Comment by helhum** [comment]
I think your are on a completely wrong path.
1. The backtrace you present has nothing to do with an eID request, it is not even related to this extension, but is a TYPO3 backend Ajax request
2. The eID does a very limited bootstrap, which does not evaluate any non installed extensions
3. The point of this extension is to spread the message to not use eID scripts. Even if there might be a bug here (which I don't think) I will not fix it
